import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import GRPOConfig, GRPOTrainer

from config import (
    MODEL_ID,
    N_RLVR_SAMPLES,
    N_TEST_SAMPLES,
    RLVR_PATH,
    SFT_PATH,
    TOKENIZER_ID,
)
from evaluate import get_decision
from pubmedqa_dataset import get_dataset


def main() -> None:
    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",
    )
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_ID)
    sft_model = PeftModel.from_pretrained(base_model, SFT_PATH)
    sft_model = sft_model.merge_and_unload()

    _, train_dataset, test_dataset = get_dataset(
        n_rlvr_samples=N_RLVR_SAMPLES, n_test_samples=N_TEST_SAMPLES, rlvr=True
    )

    # Reward Function for RLVR
    def accuracy_reward(
        completions: list[str], ground_truth: list[str], **kwargs
    ) -> list[float]:
        """
        completions: List of strings generated by the model
        ground_truth: The 'yes/no/maybe' label from the dataset
        """
        rewards = []
        for pred, target in zip(completions, ground_truth):
            if isinstance(pred, list) and len(pred) > 0 and isinstance(pred[0], dict):
                pred_text = pred[0]["content"]
            else:
                pred_text = pred
            prediction = get_decision(pred_text)
            # Binary reward: 1 for correct, 0 for wrong
            rewards.append(1.0 if prediction == target.lower() else 0.0)
        return rewards

    trainer = GRPOTrainer(
        model=sft_model,
        reward_funcs=[accuracy_reward],
        args=GRPOConfig(
            output_dir=RLVR_PATH,
            learning_rate=5e-6,
            num_generations=8,
            generation_batch_size=8,
            per_device_train_batch_size=8,  # Equal to num_generations
            gradient_accumulation_steps=4,
            max_completion_length=2048,
            logging_steps=10,
            bf16=True,
            use_liger_kernel=True,
            use_vllm=False,
        ),
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        processing_class=tokenizer,
    )

    print("Starting RLVR training")
    trainer.train()

    print(f"Saving RLVR model to {RLVR_PATH}")
    trainer.save_model(RLVR_PATH)

    # free the memory again
    del sft_model
    del trainer
    torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
