import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import GRPOConfig, GRPOTrainer

from config import (
    MODEL_ID,
    N_RLVR_SAMPLES,
    N_TEST_SAMPLES,
    RLVR_PATH,
    SFT_PATH,
    TOKENIZER_ID,
)
from hf_datasets.pubmedqa_dataset import PubMedQADataset


def main() -> None:
    base_model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",
    )
    tokenizer = AutoTokenizer.from_pretrained(TOKENIZER_ID)
    tokenizer.pad_token = tokenizer.eos_token

    base_model.config.eos_token_id = tokenizer.eos_token_id
    base_model.config.bos_token_id = tokenizer.bos_token_id
    base_model.config.pad_token_id = tokenizer.pad_token_id

    # 3. If there is a generation_config, update that too
    if hasattr(base_model, "generation_config"):
        base_model.generation_config.eos_token_id = tokenizer.eos_token_id
        base_model.generation_config.pad_token_id = tokenizer.pad_token_id

    sft_model = PeftModel.from_pretrained(base_model, SFT_PATH, is_trainable=True)

    _, train_dataset, test_dataset = PubMedQADataset().get_dataset(
        n_rlvr_samples=N_RLVR_SAMPLES, n_test_samples=N_TEST_SAMPLES, rlvr=True
    )

    # Reward Function for RLVR
    def accuracy_reward(
        completions: list[str], ground_truth: list[str], **kwargs
    ) -> list[float]:
        """
        completions: List of strings generated by the model
        ground_truth: The 'yes/no/maybe' label from the dataset
        """
        rewards = []
        for pred, target in zip(completions, ground_truth):
            if isinstance(pred, list) and len(pred) > 0 and isinstance(pred[0], dict):
                pred_text = pred[0]["content"]
            else:
                pred_text = pred
            pred_label = PubMedQADataset.get_decision(pred_text)
            score = 0.0

            if pred_label == target.lower():
                score += 1.0

            has_thinking_tag = (
                "thinking" in pred_text.lower() or "reasoning" in pred_text.lower()
            )
            if has_thinking_tag:
                score += 0.5
            else:
                score -= 0.5

            cot_keywords = [
                "because",
                "therefore",
                "suggests",
                "first",
                "second",
                "third",
                "step",
                "leads to",
                "activation of",
                "consequently",
            ]
            num_keywords = sum(1 for word in cot_keywords if word in pred_text.lower())

            # Bonus for using chain-of-thought structure
            score += min(num_keywords * 0.1, 0.4)

            score += len(pred_text) / 5000

            if len(pred_text) > 2500:
                score -= 1.0

            if len(pred_text) < 150:
                score -= 0.8

            rewards.append(score)
        return rewards

    trainer = GRPOTrainer(
        model=sft_model,
        reward_funcs=[accuracy_reward],
        args=GRPOConfig(
            output_dir=RLVR_PATH,
            save_strategy="steps",
            save_steps=25,
            save_total_limit=5,
            learning_rate=1e-6,
            lr_scheduler_type="cosine",
            warmup_ratio=0.1,
            temperature=0.8,
            beta=0.005,
            num_generations=8,  # 8 or 16
            generation_batch_size=8,  # 8 or 16
            per_device_train_batch_size=1,
            gradient_accumulation_steps=16,
            max_completion_length=768,
            logging_steps=1,
            bf16=True,
            gradient_checkpointing=True,
            use_liger_kernel=False,
            use_vllm=False,
        ),
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        processing_class=tokenizer,
    )

    print("Starting RLVR training")
    trainer.train()

    print(f"Saving RLVR model to {RLVR_PATH}")
    trainer.save_model(RLVR_PATH)

    # free the memory again
    del sft_model
    del trainer
    torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
